### ISSUE TITLE
Fallback to `vendored` build if `pkg-config` doesn't exist

### ISSUE THREAD

**Issue by ok-nick** [ssalonen/libcec-sys#12]
Convenient, easy, and makes sense. 

Edit: didn't mean to mark it as a bug.

**Comment by ssalonen** [comment]
Thanks for the comment 

This is already how it should be. From Readme 

> As a fallback, vendored libcec (v4.x) is used during the build.

**Comment by ok-nick** [comment]
You're right, my issue actually has to do with #13.
