### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by ssalonen** [ssalonen/libcec-sys#5]
## Bug description

libcec-sys compilation seems to fail, as indicated in downstream library https://github.com/ssalonen/cec-rs/pull/12

It seems that `--parallel` flag is not accepted by the `cmake` version used in the `cross` build.

In cmake 3.12, [the `--parallel` flag was introduced](https://cmake.org/cmake/help/latest/release/3.12.html#command-line). It looks like `cmake` crate (which is used in `build.rs`) started to use this new flag in https://github.com/alexcrichton/cmake-rs/pull/123. 

The error is probably due to too old `cmake` version.

Indeed, builds use docker images based on cross 0.1.16, which uses cmake 3.5.1 https://github.com/rust-embedded/cross/blob/v0.1.16/docker/cmake.sh#L4

**Comment by coral** [comment]
Can confirm that I ran into this when trying to build libcec-sys locally and assumed it was my machine but seems to be general.

**Comment by ssalonen** [comment]
thanks @coral. I will try to see if updating the docker images would help.

**Comment by ssalonen** [comment]
Hopefully resolved via https://github.com/ssalonen/libcec-sys/pull/6

We can close this issue once downstream library build succeeds.
